<?php
    $this -> headcontent = '<style type="text/css">
        .tabs-panels .panel { word-break:break-all;word-wrap:break-word; }
        pre {
                border: 2px solid #ccc; 
                background-color: #eeeeff;
                padding: 10px;
                font-size: 11px;word-break:normal;word-wrap:break-word;white-space:pre-wrap;
            }
    </style>' . PHP_EOL;
?>
<div data-options="fit:true"><?=$content?></div>