<!DOCTYPE html>
<html>
    <head>
        <title><?=$pagetitle?></title>
        <meta http-equiv="content-type" content="text/html;charset=utf-8" />
        <link rel="stylesheet" type="text/css" id="etheme" href="<?=URL_BASE?>static/js/easyui/themes/default/easyui.css" />
        <link rel="stylesheet" type="text/css" id="etheme" href="<?=URL_BASE?>static/js/easyui/themes/icon.css" />
        <script type="text/javascript" src="<?=URL_BASE?>static/js/jquery-1.7.2.min.js"></script>
        <script type="text/javascript" src="<?=URL_BASE?>static/js/easyui/jquery.easyui.min.js"></script>
        <script type="text/javascript" src="<?=URL_BASE?>static/js/easyui/locale/easyui-lang-zh_CN.js"></script>
<?php echo $headcontent; ?>
    </head>
    <body><?php echo $content ?></body>
</html>
